spring:
  datasource:
    username: ${DB_USER:username}
    password: ${DB_PASS:password}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:post_db}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: ${HIKARI_MIN_IDLE:3}
      maximumPoolSize: ${HIKARI_MAX_POOL_SIZE:50}
      idleTimeout: ${HIKARI_IDLE_TIMEOUT:60000}
      maxLifetime: ${HIKARI_MAX_LIFE_TIME:66000}
      connectionTimeout: ${HIKARI_CONN_TIMEOUT:5000}
  jpa:
    open-in-view: false
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update

